version: '3.7'

services:

  react-onboarding:
    container_name: react-onboarding
    build:
      context: .
      dockerfile: ./support/Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true